{
  "providers": ["nodejs"],
  "buildCommand": "npm install && npm run prisma:generate && npm run build",
  "startCommand": "npm run prisma:migrate:prod && npm run start",
  "nixPkgs": ["nodejs_20", "openssl"],
  "phases": {
    "setup": {
      "nixPkgs": ["nodejs_20", "openssl"]
    },
    "install": {
      "cmds": ["npm ci"]
    },
    "build": {
      "cmds": [
        "npm run prisma:generate",
        "npm run build"
      ]
    }
  }
}
